server:
  # 端口号
  port: 8080
spring:
  application:
    # 应用的名称
    name: bugulu_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bugulu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: aaaa

  redis:
    host: 192.168.10.100
    port: 6379
#    username: root
    password: aaaa
    timeout: 60000
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms



mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

bugulu:
  path: D:/code/git/bugulu_take_out/src/main/resources/static/image/